# Permalinks

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
tagline:             'Christina Leuci'
description:         '4f 68 2c 20 68 65 6c 6c 6f 20 74 68 65 72 65 2e'
url:                 https://christinaleuci.github.io
baseurl:             https://christinaleuci.github.io
paginate:            5

# About/contact
author:
  name:              Christina Leuci
  twitter:           ChristinaLeuci
  email:             christinaleuci@gmail.com
  github:            https://github.com/ChristinaLeuci

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
